apiVersion: v1
kind: Service
metadata:
  name: srv-ck-consultazona
  namespace: qa
  labels:
    app: ck-consultazona
    version: 1.0.0
    environment: qa
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: api
    port: 80
    nodePort: 30009
    protocol: TCP
    targetPort: port-ck-consultazona
  selector:
    app: ck-consultazona
    version: 1.0.0
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

